{
 "title": "Diabetes Prediction Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Model Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "model_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "model_prediction_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "model_prediction_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Latency (s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "model_prediction_latency_seconds_sum / model_prediction_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(model_prediction_requests_total[1m])",
     "legendFormat": "Requests / sec"
    }
   ]
  },
  {
   "title": "Prediction Results Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "model_prediction_result_total", "legendFormat": "{{result}}" }
   ]
  }
 ]
}